name: restreamx-plugin
arch: amd64
platform: linux
version: 0.1.0
section: default
priority: extra
maintainer: ReStreamX
description: ReStreamX MySQL plugin
contents:
  - src: ./restreamx.so
    dst: /usr/lib/mysql/plugin/restreamx.so
  - src: ./mysql-plugin/packaging/restreamx.install.sql
    dst: /usr/share/restreamx/restreamx.install.sql
  - src: ./mysql-plugin/packaging/restreamx.uninstall.sql
    dst: /usr/share/restreamx/restreamx.uninstall.sql
